integrate the broker adapter into the wallet data
in2workspace/wallet-data pull request #19
Opened 2024-01-02 13:23 UTC by rubenmodamioin2

2024-01-03 14:26 UTC, oriolcanadesin2 requested changes

2024-01-03 14:26 UTC, oriolcanadesin2 commented on CHANGELOG.md
> +## [v2.1.0](https://github.com/in2workspace/wallet-data/releases/tag/v2.1.0) - unreleased
Add to v2.0.0

2024-01-03 14:26 UTC, oriolcanadesin2 commented on README.md
> +The project is currently at version **2.1.0** and is in a stable state.
change to v2.0.0

2024-01-03 14:26 UTC, oriolcanadesin2 commented on build.gradle
> +version = '2.1.0'
change to v2.0.0

2024-01-03 14:26 UTC, oriolcanadesin2 commented on src/main/java/es/in2/walletdata/controller/UserController.java
> +        return Utils.getUserIdFromToken(authorizationHeader)
Why you need to use 'Utils'? Isn't a public static method?

2024-01-04 07:06 UTC, rubenmodamioin2 commented on src/main/java/es/in2/walletdata/controller/UserController.java
> +        return Utils.getUserIdFromToken(authorizationHeader)
solved

2024-01-04 07:06 UTC, rubenmodamioin2 commented on build.gradle
> +version = '2.1.0'
solved

2024-01-04 07:06 UTC, rubenmodamioin2 commented on README.md
> +The project is currently at version **2.1.0** and is in a stable state.
solved

2024-01-04 07:06 UTC, rubenmodamioin2 commented on CHANGELOG.md
> +## [v2.1.0](https://github.com/in2workspace/wallet-data/releases/tag/v2.1.0) - unreleased
solved

2024-01-04 07:14 UTC, oriolcanadesin2 approved these changes

2024-01-04 08:48 UTC, oriolcanadesin2 approved these changes

2024-01-04 09:33 UTC, merged